-- 조인

SELECT * 
FROM STUDENT;
SELECT * 
FROM ENROL;
SELECT *
FROM SUBJECT;

SELECT *
FROM STUDENT
INNER JOIN ENROL ON STUDENT.STU_NO = ENROL.STU_NO;

SELECT S.STU_NO, STU_NAME, ENR_GRADE, SUB_NO
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;

SELECT S.STU_NO, STU_NAME, ENR_GRADE, E.SUB_NO, SUB_NAME
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON SUB.SUB_NO = E.SUB_NO;

SELECT * 
FROM EMP;
SELECT *
FROM DEPT;
SELECT * 
FROM SALGRADE;


-- 사번, 이름, 급여, 부서이름 출력
SELECT EMPNO, ENAME, SAL, DNAME
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

SELECT EMPNO, ENAME, SAL, GRADE
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;

-- STUDENT, ENROL, SUBJECT
-- 1. 학생들의 시험 평균 점수 구하기(학번, 이름, 평균점수)
SELECT S.STU_NO, STU_NAME, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME;
-- 2. 학과별 시험 평균점수 구하기
SELECT STU_DEPT, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_DEPT;


