-- SELECT, INSERT, UPDATE, DELETE

SELECT *
FROM STUDENT
WHERE STU_GENDER = 'M' AND STU_DEPT = '전기전자';

SELECT *
FROM STUDENT
WHERE STU_HEIGHT >= 170;

SELECT * 
FROM STUDENT
WHERE STU_HEIGHT IS NULL; -- IS NOT NULL

SELECT *
FROM STUDENT
WHERE SUBSTR(STU_NO, 3, 2) = 15;

SELECT *
FROM STUDENT
ORDER BY STU_HEIGHT ASC; -- DESC

SELECT *
FROM STUDENT
ORDER BY STU_GRADE, STU_CLASS;

SELECT *
FROM STUDENT
WHERE STU_GENDER = 'M'
ORDER BY STU_HEIGHT;

SELECT STU_NO AS "학번 ASDF", STU_NAME 이름, STU_DEPT 학과
FROM STUDENT;

-- 키가 165~175 사이의 학생들을 출력
SELECT *
FROM STUDENT
WHERE STU_HEIGHT BETWEEN 165 AND 175;
-- WHERE STU_HEIGHT >= 165 AND STU_HEIGHT <= 175;

SELECT *
FROM PROFESSOR
WHERE POSITION IN ('정교수', '조교수');
-- WHERE POSITION = '정교수' OR POSITION = '조교수';

SELECT *
FROM PROFESSOR
WHERE POSITION LIKE '%교수%';
