-- INSERT, UPDATE, DELETE
SELECT * FROM STUDENT;

-- INSERT 컬럼 정의하는 방법
INSERT INTO STUDENT(STU_NO, STU_NAME, STU_DEPT)
VALUES(12345678, '홍길동', '기계');
COMMIT;

-- INSERT 컬럼 생략(모든 컬럼의 값을 넣어야 함)
INSERT INTO STUDENT
VALUES(12341234, '김철수', '전기전자', 1, 'A', 'M', 170, NULL);

-- 학번이 12345678 (홍길동)인 학생의 학과를 '컴퓨터정보', 학년을 1, CLASS를 'A'로 수정
UPDATE STUDENT SET
STU_DEPT = '컴퓨터정보',
STU_GRADE = 1,
STU_CLASS = 'A'
WHERE STU_NO = 12345678;
COMMIT;

-- DELETE
-- 학번이 12341234 이 학생 삭제
DELETE FROM STUDENT WHERE STU_NO = '12341234';
COMMIT;
SELECT * FROM STUDENT;





