-- 
SELECT DECODE(SUBSTR(JUMIN, 7, 1), 1, '남자', '여자')
FROM STU;

INSERT INTO BOARD
VALUES (1, '오라클 재밌다', '뻥인데', SYSDATE, SYSDATE);
COMMIT;
-- 2026.02.27. 15:41
SELECT TO_CHAR(CDATETIME, 'YYYY.MM.DD HH24:MI') 
FROM BOARD;

SELECT MAX(STU_HEIGHT)
FROM STUDENT;

SELECT ROUND(AVG(SAL), 2)
FROM EMP;

SELECT *
FROM EMP
WHERE SAL = (
    SELECT MAX(SAL)
    FROM EMP
);

SELECT JOB, ROUND(AVG(SAL), 2)
FROM EMP
WHERE SAL >= 1500
GROUP BY JOB
HAVING AVG(SAL) >= 2500;

SELECT S.STU_NO, STU_NAME, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME;

SELECT S.STU_NO, AVG(ENR_GRADE) AVG_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO;

SELECT *
FROM STUDENT S
INNER JOIN (
    SELECT S.STU_NO, AVG(ENR_GRADE) AVG_GRADE
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY S.STU_NO
) T ON S.STU_NO = T.STU_NO;

SELECT S.*, ENR_GRADE
FROM STUDENT S 
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;


SELECT E1.*, E2.ENAME 매니저이름
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;

SELECT *
FROM DEPARTMENT;

SELECT * 
FROM STU S
INNER JOIN DEPARTMENT D1 ON S.DEPTNO1 = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
WHERE NAME = '서진수';


SELECT *
FROM EMP E
INNER JOIN SALGRADE ON E.SAL BETWEEN LOSAL AND HISAL;


