-- STUDENT, ENROL, SUBJECT
-- 1. 학번, 학생이름, 학과, 시험과목명, 시험점수 출력
SELECT S.STU_NO, STU_NAME, STU_dEPT, SUB_NAME, ENR_GRADE
FROM STUDENT S 
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO;
-- 2. 각 학과별 시험 평균 점수 구하기(학과,평균점수 출력)
SELECT STU_DEPT, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_DEPT;

-- 3. 본인 학과의 시험 평균 점수보다 높은 평균 점수를 가진 학생의 학번, 이름, 평균점수 출력
SELECT S.STU_NO, STU_NAME, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN (
    SELECT STU_DEPT, AVG(ENR_GRADE) AVG_DEPT
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY STU_DEPT
) T ON S.STU_DEPT = T.STU_DEPT
GROUP BY S.STU_NO, STU_NAME, AVG_DEPT
HAVING AVG(ENR_GRADE) > AVG_DEPT;

-- 4. 시험을 2번이상 본 학생의 학번, 이름, 시험본 횟수 출력
SELECT S.STU_NO, STU_NAME, COUNT(*)
FROM STUDENT S 
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME
HAVING COUNT(*) >= 2;




