-- SEQUENCE 
CREATE SEQUENCE TEMP_SEQ
    INCREMENT BY 1
    START WITH 1;
    -- MINVALUE 1
    -- MAXVALUE 99999
    -- NOCYCLE;
    
SELECT TEMP_SEQ.NEXTVAL
FROM DUAL;

CREATE TABLE BOARD(
  BOARDNO NUMBER PRIMARY KEY,
  TITLE VARCHAR2(100),
  CONTENTS VARCHAR2(300),
  CDATETIME DATE,
  UDATETIME DATE
);
COMMIT;

ROLLBACK;

CREATE SEQUENCE BOARD_SEQ
    INCREMENT BY 1
    START WITH 1;

INSERT INTO BOARD
VALUES(BOARD_SEQ.NEXTVAL, '333 게시글', '안녕?', SYSDATE, SYSDATE);
SELECT * FROM BOARD;





