-- EMP
-- 1. 내 부서의 평균 급여보다 높은 급여를 받는 사람 출력

SELECT *
FROM EMP E
INNER JOIN (
    SELECT DEPTNO, AVG(SAL) AS AVG_SAL
    FROM EMP
    GROUP BY DEPTNO
) T ON E.DEPTNO = T.DEPTNO
WHERE SAL > AVG_SAL;


-- 3. 본인 학과의 시험 평균 점수보다 높은 평균 점수를 가진 학생의 학번, 이름, 평균점수 출력

SELECT S.STU_NO, STU_NAME, AVG(ENR_GRADE), AVG_GRADE
FROM STUDENT S 
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN (
    SELECT STU_DEPT, AVG(ENR_GRADE) AS AVG_GRADE
    FROM STUDENT S 
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY STU_DEPT
)T ON S.STU_DEPT = T.STU_DEPT
GROUP BY S.STU_NO, STU_NAME, AVG_GRADE
HAVING AVG(ENR_GRADE) > AVG_GRADE
;

-- 사용자가 작성한 게시글 조회수의 총합이
-- 모든 게시글 조회수 전체 평균보다 높은 
-- 작성자 아이디, 이름, 조회수 총합 출력

SELECT B.USERID, U.USERNAME, SUM(CNT)
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
GROUP BY B.USERID, U.USERNAME
HAVING SUM(CNT) > (
    SELECT AVG(CNT)
    FROM TBL_BOARD
);





