SELECT * FROM TBL_EMP;
SELECT * FROM TBL_DEPT;
SELECT * FROM TBL_PROJECT;
SELECT * FROM TBL_ASSIGNMENT;

-- 5. 각 부서별 평균 금여를 구한 후 평균 급여를 기준으로 내림차순 하시오. ( 10점 )
-- 사용테이블 : TBL_EMP, TBL_DEPT
-- 출력 컬럼 : 부서 이름, 평균 급여
SELECT DEPT_NAME, AVG(SALARY) SAL
FROM TBL_EMP E
INNER JOIN TBL_DEPT D ON E.DEPT_ID = D.DEPT_ID
GROUP BY DEPT_NAME
ORDER BY SAL DESC;

-- 6. 모든 부서장들의 급여 평균보다 높은 급여를 받는 직원들을 출력하시오. ( 10점 )
--   : TBL_EMP, TBL_DEPT
-- 출력 컬럼 : 직원 이름, 급여, 부서장들의 평균 급여

SELECT 
    EMP_NAME, SALARY, AVG_SAL
FROM TBL_EMP E
INNER JOIN (
    SELECT AVG(SALARY) AS AVG_SAL
    FROM TBL_EMP E
    INNER JOIN TBL_DEPT D ON E.EMP_ID = D.HEAD_ID
) T ON 1=1
WHERE SALARY > AVG_SAL;

SELECT 
    EMP_NAME, SALARY, ROUND(AVG_SAL, 1)
FROM TBL_EMP E
INNER JOIN (
    SELECT AVG(SALARY) AS AVG_SAL
    FROM TBL_EMP E
    INNER JOIN TBL_DEPT D ON E.EMP_ID = D.HEAD_ID
) T ON SALARY > AVG_SAL;

SELECT 
    EMP_NAME, 
    SALARY,
    (
        SELECT AVG(SALARY) AS AVG_SAL
        FROM TBL_EMP E
        INNER JOIN TBL_DEPT D ON E.EMP_ID = D.HEAD_ID
    )
FROM TBL_EMP 
WHERE SALARY > (
    SELECT AVG(SALARY) AS AVG_SAL
    FROM TBL_EMP E
    INNER JOIN TBL_DEPT D ON E.EMP_ID = D.HEAD_ID
);

-- 7. '모바일 앱 개발' 프로젝트에 배정된 직원들중 가장 높은 급여를 받는 직원을 출력하시오. ( 5점 )
-- 사용 테이블 : TBL_EMP, TBL_PROJECT, TBL_ASSIGNMENT
-- 출력 컬럼 : 직원 이름, 직급, 급여

SELECT *
FROM TBL_EMP E
WHERE SALARY = (
    SELECT MAX(SALARY)
    FROM TBL_PROJECT P
    INNER JOIN TBL_ASSIGNMENT A ON P.PROJ_ID = A.PROJ_ID
    INNER JOIN TBL_EMP E ON E.EMP_ID = A.EMP_ID
    WHERE PROJ_NAME = '모바일 앱 개발'
);

SELECT *
FROM TBL_PROJECT P
INNER JOIN TBL_ASSIGNMENT A ON P.PROJ_ID = A.PROJ_ID
INNER JOIN TBL_EMP E ON E.EMP_ID = A.EMP_ID
WHERE PROJ_NAME = '모바일 앱 개발' AND SALARY = (
    SELECT MAX(SALARY)
    FROM TBL_PROJECT P
    INNER JOIN TBL_ASSIGNMENT A ON P.PROJ_ID = A.PROJ_ID
    INNER JOIN TBL_EMP E ON E.EMP_ID = A.EMP_ID
    WHERE PROJ_NAME = '모바일 앱 개발'
);


SELECT *
FROM TBL_EMP E
INNER JOIN (
    SELECT MAX(SALARY) MAX_SAL
    FROM TBL_PROJECT P
    INNER JOIN TBL_ASSIGNMENT A ON P.PROJ_ID = A.PROJ_ID
    INNER JOIN TBL_EMP E ON E.EMP_ID = A.EMP_ID
    WHERE PROJ_NAME = '모바일 앱 개발'
) T ON E.SALARY = MAX_SAL;



SELECT * FROM TBL_ASSIGNMENT;


-- 8. 각 직원의 부하직원의 수(자신의 emp_id를 manager_id로 가지고 있는 사람 수)를 구하시오. 단, 없으면 0으로 출력하시오. ( 5점 )
-- 사용 테이블 : TBL_EMP
-- 출력 컬럼 : 직원 이름, 직급, 부하직원 수

SELECT E1.EMP_NAME, E1.JOB_TITLE ,COUNT(E2.EMP_ID)
FROM TBL_EMP E1
LEFT JOIN TBL_EMP E2 ON E1.EMP_ID = E2.MANAGER_ID
GROUP BY E1.EMP_NAME, E1.JOB_TITLE;


